### ISSUE TITLE
Some demo apps return "Not found" and seem to be broken

### ISSUE THREAD

**Issue by dredozubov** [urweb/urweb#130] opened 2018-06-15 13:15 UTC
I'm getting a "Not found" page from the `nested` demo there: http://www.impredicative.com/ur/demo/
I can reproduce it locally by building the demo app with `The Ur/Web compiler, version 20170720`. I get the same result by building the `upload` app locally as well although it works fine at http://www.impredicative.com. I'm currently getting my feet wet with Ur/Web, so I can't pinpoint the cause of the issue myself, but it may be the case that I need to update the compiler itself.

**Comment by achlipala** [comment] 2018-06-15 15:46
Can you give me a script (informal) to reproduce the problem?  I didn't have any issues using the Upload example just now.

**Comment by dredozubov** [comment] 2018-06-15 16:20
I create an empty directory, then create 3 files as listed in this gist: https://gist.github.com/dredozubov/a11f84bff87ca1335d57b3bfc60f0ddd

I run `urweb upload && ./upload.exe`, open the `http://localhost:8080` and see the page saying "Not found".

**Comment by achlipala** [comment] 2018-06-15 16:21
Was there some documentation suggesting that the page would be found at that URL?  It would be `http://localhost:8080/Upload/main`.

**Comment by dredozubov** [comment] 2018-06-15 16:27
I see.  Can you please point me to any explanation of how routes actually work? The `nested` demo seems to be broken on the website though.

**Comment by achlipala** [comment] 2018-06-15 16:31
Oh, yes, the Nested demo _is_ really broken!  I'll put that on my to-do list to look into.

You'll find the explanation of routing in Section 10 of [the reference manual](http://www.impredicative.com/ur/manual.pdf).

**Comment by achlipala** [comment] 2018-06-16 17:34
Somewhere along the line, a change to the handling of URL-handler aliasing created this issue (for the Nested demo), which only arose because code outside an Ur/Web app was computing URL prefixes.  (The compiler still did correctly rule out dangling links within an Ur/Web app!)  It's fixed now.

**Closed by achlipala** 2018-06-16 17:34 UTC
