### ISSUE TITLE
css classes not recognized from locally hosted file

### ISSUE THREAD

**Issue by wvhulle** [urweb/urweb#78] opened 2017-04-27 19:07 UTC
I am using urweb 20160213 on debian. I am following a [tutorial](http://expdev.net/urtutorial/) to learn more about urweb. Meanwhile did some adjustments to the configuration. My `urp` file now contains the code

```
database dbname=sigual
sql sigual.sql
file /sigual.css sigual.css
rewrite style Sigual/*

sigual
```

It refers to a local file similar to the [css](https://github.com/gian/urtutorial/raw/master/step3/style.css) from the tutorial with some added subclasses `.topnav` and `.feed` to `body`. I declared these as `style topnav` etc. in my `ur`-file and used them in code as `<div class={topnav}>`. After editing the css file and recompiling with urweb, the new css file is not served, but the old one.

Now I am trying to do serve a css file locally with the chatroom tutorial in the latest urweb paper and I experience similar problems. I do not experience this problem when I use a [remote css file](https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css) like boostrap's.

**Comment by wvhulle** [comment] 2017-04-27 19:17
I do not experience this problem when I use a remote css file like https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css

**Comment by achlipala** [comment] 2017-05-03 00:57
Have you confirmed with a tool like `wget` that the Ur/Web server is truly returning old files, and the issue isn't just caching in the browser?  I'm open to suggestions of how to change how Ur/Web programs respond to HTTP requests, including using different headers or values for them!

**Comment by achlipala** [comment] 2017-07-12 19:24
I'll close this one soon with no further discussion.  The issue could very well be outside Ur/Web's purview.

**Closed** 2017-10-01 20:40 UTC
